version: '3'

services:
  app:
    build: ./app
    depends_on:
      - db

  db:
    image: redis:6
    volumes:
      - ./db/redis.conf:/usr/local/etc/redis/redis.conf
      - /home/bruger/redis/:/redis/
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass reganvest
